# Generated by Django 4.1.1 on 2022-10-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bench', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park', to='bench.bench1')),
                ('bench2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park', to='bench.bench2')),
                ('bench3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park', to='bench.bench3')),
            ],
        ),
    ]
